name: RPGEngine
version: 1.0.1
main: fr.doryamy.rpgengine.RpgEngine
api-version: '1.21.1'
author: DoryAmy

depend:
  - Citizens

commands:
  rpg:
    description: Commande principale de RPGEngine
    usage: /rpg
    permission: rpg.admin

permissions:
  rpg.admin:
    description: Administration de RPGEngine
    default: op